version: "3.9"
services:
  db:
    image: postgis/postgis:16-3.4
    container_name: crisis_db
    environment:
      POSTGRES_USER: crisis
      POSTGRES_PASSWORD: crisis123
      POSTGRES_DB: crisis
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
